Fix UnboundLocalError generating a diff (#390)
This happens when two resources of different kind are compared
or if 'kind' is missing in the dict.

Traceback (most recent call last):
   File "/tmp/ansible_k8s_payload_trnxlugx/ansible_k8s_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s.py", line 320, in <module>
   File "/tmp/ansible_k8s_payload_trnxlugx/ansible_k8s_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s.py", line 316, in main
   File "/tmp/ansible_k8s_payload_trnxlugx/ansible_k8s_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/common.py", line 548, in execute_module
   File "/tmp/ansible_k8s_payload_trnxlugx/ansible_k8s_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/common.py", line 760, in perform_action
   File "/tmp/ansible_k8s_payload_trnxlugx/ansible_k8s_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/common.py", line 347, in diff_objects
   File "/home/linosteiner/.local/lib/python3.9/site-packages/openshift/dynamic/apply.py", line 232, in recursive_diff
      result = recursive_list_diff(dict1[k], dict2[k], this_position)
UnboundLocalError: local variable 'this_position' referenced before assignment