Call functions on resource fields if they don't exist as name
`resource.get(key, default)` should call `resource.__dict__.get(key, default)`
rather than `resource.__dict__.__getitem__('get')` assuming 'get' is not
a key of `resource`.

Because e.g. resource.items is ambiguous, favour
`resource.__dict__.__getitem__('items')` over `resource.__dict__.items()`
but fallback to the latter

Before:
```
>>> dep.status.get('unavailableReplicas')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```
After:
```
>>> dep.status.get('unavailableReplicas', 0)
0
```