Fix apply to cope better with missing last_applied entries
If desired and actual contain a dict structure that is missing
from last_applied, continue rather than crashing with

AttributeError: 'NoneType' object has no attribute 'get'